INDEXING AND SLICING 


In [4]:
import numpy as np 

In [62]:
a1 = np.arange(8)
a2 = np.arange(12).reshape(4,3)
a3 = np.linspace(1,12,num = 12).reshape(2,2,3).astype(int)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [64]:
# for indexing the 1D array you can just do as the thing that we had done in pythoon normally 
print(a1[-1])

# for 2D array we have to give the indexong of the rows and column to extract the elements 

print(a2[1,2]) 

# for 3D array we have to understand how 3D array are formed so basically in 3D array there is depth so we have to index depth and other process is same 
# as 2D array for example we are indexing a3 

print(a3[0,1,2])

# ROW IS THE HORIZONTAL WHILE THE COLUMN IS VERTICAL 

7
5
6


SLICING OF 1D ARRAY 

In [74]:
# SLICING IS THE PROCESS OF TAKING OUT MULTIPLE DATA BY GIVING ITS INDEX 
print(a1[2:5]) # THIS IS SLICING PROCESS IN 1D ARRAY 
print(a1[2:6:2]) # this will print the value of 2nd index and leave 2 index and again print the value of the next index 
print(a1[2:]) # this will print all the index from 2 to the last element 

[2 3 4]
[2 4]
[2 3 4 5 6 7]


SLICING OF 2D ARRAY 

In [78]:
print(a2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [125]:
# now i want to get 1 ,4 , 7 ,10 in the output then the syntax i would use is 
print(a2[:,1])

# if i want to get the first row which is 0,1,2 then i have to write  the following code 
print(a2[0,:])

# if i want to get the individual element then 
print(a2[2,1])

# if i want to get 6,7 and 9,10 as an output then 

print(a2[2:,0:2])

# similarly if i want to get 7,8 and 11,12 then i would do 
print(a2[2:,1:])

# if i want to get 0 ,2 , 9, 11 then i would do 
print(a2[::3,::2])

# if i only want to get 6 and 8 then 
print(a2[2,::2])

[ 1  4  7 10]
[0 1 2]
7
[[ 6  7]
 [ 9 10]]
[[ 7  8]
 [10 11]]
[[ 0  2]
 [ 9 11]]
[6 8]


SLICING OF 3D ARRAY 

In [131]:
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# here i want to print 7 then the code i will write is 
print(a3[1,0,0])

# if i want to print 9,12 then the code i will write is

print(a3[1,:,2])

# if i want to print 8,9 then 

print (a3[1,0,1:])

# if i want to print 7,8,10,11 then i will write 

print(a3[1,:,:2])

# if i want to print 1,3 and 7,9 then i will write the following code

print(a3[:,0,::2])

In [6]:
# some more practice 
a4 = np.arange(27).reshape(3,3,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
# here i want to print 0,2,9,11,18,20
#print(a4[:,0,0:3:2])

# if i want the output od 0,2,12,14,21,23 then i will write 
#print(a4[0,0,::2],a4[1,1,::2],a4[2,1,::2])

# we can achieve the output by another method also 
print(a4[[0,1,2],[0,1,1],::2])



[[ 0  2]
 [12 14]
 [21 23]]


ITERATING IN NUMPY ARRAY 

In [206]:
#iteration in 1D array 
for i in a1 :
    print(i)
# this will give2 each items

0
1
2
3
4
5
6
7


In [208]:
#iteration in 2D arrays 
for i in a2 :
    print(i)
#THIS WILL GIVE THE ITERATION IN 1D ARRAY 

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [210]:
#ITERATION IN 3D ARRAY 
for i in a3 :
    print(i)
# this will give the output in the 2D array 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [212]:
# to print the individual numbers in 2D array we can usse nd.iter function 
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


HORIZONTAL AND VERTICAL STACKING 

In [236]:
# horizontal stacking 
# it will stack the arrays in the horizontal way for example 
a5 = np.arange(0,12).reshape(3,4)
a6 = np.arange(12,24).reshape(3,4)
print(np.hstack((a5,a6)))

# there is only one requirement for the stacking that the shape of the array should be the same 
#np.vstack wil stack the output vertically 
print(np.vstack((a5,a6))) 

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


HORIZONTAL AND VERTICAL SPLITING 

In [240]:
print(np.hsplit(a5,2))
# it will split the arrays here in the example the prameters are the arrays name and another example is the no of parts you want to divide the array 

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [248]:
#  VSPLIT
#hsplit also works in the same way 
print(np.vsplit(a6,3))

[array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
