In [6]:
import numpy as np 

# np.sort
Return andnd sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [14]:
# it makes the array in the ascending order 
a1 = np.arange(10)
a2 = np.random.randint(1,100,12).reshape(4,3)
print(a2)
print(np.sort(a1))
print(np.sort(a2))
print(np.sort(a2,axis = 0)) # this shorts in axis = 0  which is row 
# to sort in descending order we have to do 
print(np.sort(a1)[::-1])

[[33 73 16]
 [31 40 60]
 [35 87 66]
 [64 46 77]]
[0 1 2 3 4 5 6 7 8 9]
[[16 33 73]
 [31 40 60]
 [35 66 87]
 [46 64 77]]
[[31 40 16]
 [33 46 60]
 [35 73 66]
 [64 87 77]]
[9 8 7 6 5 4 3 2 1 0]


# np.append :
The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

np.index :
it is used to insert the cretain values at the certain indexing 

The np.insert() function in NumPy allows you to insert values into an array at specified indices. Here are the parameters of the np.insert() function:

Syntax:
python
Copy code
numpy.insert(arr, obj, values, axis=None)
Parameters:
arr:

Type: array_like
The input array into which you want to insert values.
obj:

Type: int, array-like of ints
Specifies the index (or indices) before which the value is to be inserted.
If it's a single integer, the value will be inserted before that index.
If it's an array of indices, the values are inserted before each corresponding index.
values:

Type: array_like
The values to insert into the array.
If the axis is specified, values should have the same shape as arr, except at the dimension corresponding to the axis.
If axis is not specified, values are flattened before insertion.
axis (optional):

Type: int, optional (default: None)
The axis along which to insert the values.
If axis=None, the array is flattened, and the values are inserted into the flattened array.
If an axis is specified, values will be inserted along that axis


In [10]:
np.append(a1,100)
# this will add 100 to the last element of the array 
# to index the value at the cretain index we can do the following 
new_array = np.insert(a1,3,100)
print(new_array)

[  0   1   2 100   3   4   5   6   7   8   9]


In [23]:
# for 2D arrays we can do by doing this 
np.append (a2,np.ones((a2.shape[0],1)),axis=1)



array([[44., 17., 42.,  1.],
       [69.,  8., 79.,  1.],
       [96., 12., 82.,  1.],
       [62., 38., 38.,  1.]])

# np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [25]:
c = np.arange(1,7).reshape(3,2)
d = np.random.randint(1,100,6).reshape(3,2)
print(np.concatenate((c,d),axis = 0))
print(np.concatenate((c,d),axis = 1))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [16 19]
 [67 36]
 [79  9]]
[[ 1  2 16 19]
 [ 3  4 67 36]
 [ 5  6 79  9]]


# np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/




In [46]:
e = np.array((1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,6,6,6,6,6))
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html



In [18]:
np.expand_dims(a1,axis=0)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

# np.where
The numpy.where(a1) function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

# np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.h

[ ]


np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html



np.percentile
numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

np.histogram
Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html
[ ]


np.corrcoef
Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html