# Creating Numpy array

In [19]:
import numpy as np 

In [125]:

oneD_array = np.array ([1,2,3,4,5,6,7,8])
print(oneD_array)
print(type(oneD_array))

#similarly for 2D or more dimensional arrays we can create 2D or more Dimensional lists

# WE CAN MAKE THE ARRAY HAVING ONE DATA TYPE ALSO 

B = np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype = float)
print(B)

#THIS WILL CREATE THE FLOAT DATATYPE 


[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


ARANGE AND RESHAPE 


In [108]:
#range fucntions of numpy array 
#np.aragne
a = np.arange(1,11)
print(a)
type(a)
#THIS WILL ALSO CREATE AN NUMPY ARRAY AND IT WORKS SIMILAR TO THE RANGE FUNCTIONS 


#np.reshape
# WHEN WE USE RESHAPE IT WILL CREATE THE MULTIDIMENSIONAL ARRAYS it takes 2 arguments rows and columns 
print(np.arange(1,11) . reshape (5,2))

# THE RESHAPE FUNCTION WILL ONLY WORK IF THE PRODUCT OF ROWS AND THE COLUMNS OF THE RESHAPE IS EQUAL TO THE NUMBER OF ELEMENTS 
# OF THE ARANGE FUNCTIONS 
# we can also make 3D arrays by using arange 

b = np.arange (1,13) . reshape (2,3,2)  # this will make 2 layers 
print(b)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


NP.ONES AND NP.ZEROS

In [76]:
#np.ones is used to make an array which contains all the element 1 and similarly np.zero makes 0 
# they take 2 qarguments one is for the row and another is for the columns 

a = np.ones ((3,4)) # this will make the array of 3 rows and 4 columns 
# it takes tuples as an arguments 
print(a)

b = np.zeros((3,4))
print(b) # this will also make the array of 3 rows and 4 columns but the array will be of all the zero elements 

# IT IS MAINLY USED TO INNITIALIZE THE VALUES 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


NP.RANDOMS


In [80]:
#NP.RANDOM IS ALSO USED TO INNITIALIZE THE VALUES BUT IT GENERATES THE RAANDOM VALUES 
# IT GENERATES THE VALUE IN BETWEEN O AND 1 

a = np.random.random((3,4))
print(a)


[[0.45812099 0.32554194 0.30155884 0.02142855]
 [0.13679162 0.49299257 0.75112154 0.84816071]
 [0.40204006 0.49258113 0.60251994 0.62370246]]


NP.LINSPACE


In [113]:
# np.linspace also works as an range fucntion 

a = np.linspace (-10,10,8)
#SO WHAT THIS CODE WILL DO IS THAT IT TAKES 8 ELEMENTS FROM THE RANGE OF -10 TO 10 AND RANDOMLY GENERATE 8 NUMBERS 
#IT SEPERATES THE POINT LINEARLY MEANS IT SEPERATES THE NUMBERS BY EQUAL DISTANCE FOR REFRENCE SEE THE OUTPUT OF THIS SHELL 
print(a)

[-10.          -7.14285714  -4.28571429  -1.42857143   1.42857143
   4.28571429   7.14285714  10.        ]


NP.IDENTITY

In [116]:
# np.identity makes the identity matrix 
a = np.identity (3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


NUMY ARRAY ATTRIBUTES


In [33]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float ).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

NDIM

In [165]:
# ndim is used to get the dimension of the array for eg 

a1.ndim  # it gives output 1 because the array is one dimensional 
a2.ndim # it gives the output 2 because the arrray is 2 dimensional 

2

SHAPE


In [41]:
# it gives us the shape of the array 

a1.shape
a2.shape
# it gives us the number of rows and columns of the array or matrices 

(3, 4)

SIZE AND ITEMSIZE


In [181]:
# size gives us the size fo the array and itemsize gives us how many memory is occupied by the array 
print(a1.size)   # it gives us the number of elements or the size of the array 
a2.itemsize      # this gives us how many bytes has the array occupied in the memory 
#THE SIZE IS IN BYTE 


10


8

DTYPE


In [39]:
# WE CAN ALSO SEE THE DATATYPE OF THE NUMPY ARRAY BY DOING .dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


CHANGING DATATYPE OF THE ARRAY 


In [37]:
# we can use astype to change the datatype of the numpy array 
a1.astype (np.int64)
print(a1.dtype)

int32


FOR ARITHMETIC OPERATIONS WE CAN PERFORM ANY OPERATIONS WHICH IS SUPPORTED IN PYTHON 

MIN MAX SUM AND PRODUCT 

In [43]:
# np.min IT GIVES THE SMALLEST ELEMENT IN THE NUMPY ARRAY 
# np.max IT GIVES US THE LARGEST EEMENT OF AN ARRAY 
# np.sum IT GIVES US THE SUM OF ALL THE ELEMENT OF AN ARRAY 
# np. product IT GIVES US THE PRODUCT OF ALL THE ELEMENT OF AN ARRAY 
np.sum(a2,axis = 0)

# AL THE FUNCTIONS TAKES AXIS AS AN PARAMETER IF AXIS = 0 IT SOLVES ROW AND IF AXIS = 1 IT SOLVES COLUMN 


array([12., 15., 18., 21.])

SOME STATISTICS FUNCTION 

In [ ]:
# np.mean , np.median ,np.std ,np.var 


DOT PRODUCTS 

In [54]:
# we can only use dot product if the number of row of array 1 is equal to the number of rows of array 2 for eg :
array1 = np.random.random(6).reshape(2,3)
array2 = np.arange(3,9).reshape(3,2)
np.dot(array1,array2)

# this will give us the dot product of the array 1 and array 2 


array([[ 4.87724941,  6.0998814 ],
       [ 8.67609799, 10.15686849]])

SOME OTHER NUMPY FUNCTIONS 

In [57]:
# np.round (it round up or round downs to the nearest value )
# np.floor (it round down the value )
# np.ceil (it rounds up the value )
# np.log (it gives us the log value of every arrays element )
# np.exp (it gives us the exponential value of the arrays element )


INDEXING AND SLICING OF NUMPY ARRAYS 